easy_admin:
    entities:
        # List the entity class name you want to manage
      User: 
        class: src\Entity\User
        list:
          actions:
            - {name: 'delete'}
            - {name: 'edit'}
            - {name: 'ban'}
